// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLvjVJXZTE5jm_rjWTuFyFJzt5t5sNnUs',
    appId: '1:1018081051631:web:b46c4eb34ff9824bccac1a',
    messagingSenderId: '1018081051631',
    projectId: 'parking-app-e6c5e',
    authDomain: 'parking-app-e6c5e.firebaseapp.com',
    storageBucket: 'parking-app-e6c5e.firebasestorage.app',
    measurementId: 'G-LLC8X5BPQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSQaOeHlXunzZ7a6NeIkIZ6QGx83s4J0',
    appId: '1:1018081051631:android:3a8b119a1e438392ccac1a',
    messagingSenderId: '1018081051631',
    projectId: 'parking-app-e6c5e',
    storageBucket: 'parking-app-e6c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN4r22snEy8i-sh50qmk9K8BbRokREISI',
    appId: '1:1018081051631:ios:fa3842fc5d87b985ccac1a',
    messagingSenderId: '1018081051631',
    projectId: 'parking-app-e6c5e',
    storageBucket: 'parking-app-e6c5e.firebasestorage.app',
    iosClientId: '1018081051631-9bsbv26m175kmo1qrdbd1lf868vr58g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN4r22snEy8i-sh50qmk9K8BbRokREISI',
    appId: '1:1018081051631:ios:fa3842fc5d87b985ccac1a',
    messagingSenderId: '1018081051631',
    projectId: 'parking-app-e6c5e',
    storageBucket: 'parking-app-e6c5e.firebasestorage.app',
    iosClientId: '1018081051631-9bsbv26m175kmo1qrdbd1lf868vr58g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLvjVJXZTE5jm_rjWTuFyFJzt5t5sNnUs',
    appId: '1:1018081051631:web:af66afd717dcc661ccac1a',
    messagingSenderId: '1018081051631',
    projectId: 'parking-app-e6c5e',
    authDomain: 'parking-app-e6c5e.firebaseapp.com',
    storageBucket: 'parking-app-e6c5e.firebasestorage.app',
    measurementId: 'G-5JHFN7J1GW',
  );

}